### PR TITLE
was overriding API delete message

### PR DESCRIPTION
**Pull request by snacktavish**
I had one change I forgot to commit! This prevents overriding the automatic commit message with 'study deletion'.

### CODE REVIEW

**Comment by jimallman** [comment]
It might be a good idea to add some comments (and confirm the expected results) in [the test code](https://github.com/OpenTreeOfLife/phylesystem-api/blob/a756bbf6ac362f8db0d1008cbd8fd54495924c45/ws-tests/test_study_create_delete_message.py), with three cases:
- no commit message
- empty string as commit message
- non-empty commit message (currently used, but not verified)

If only whitespace is entered in UI, it's trimmed so only an empty string ("") will be submitted. It's probably best to test for False instead of None:
```python
         commit_msg = kwargs.get('commit_msg', '')
         if not commit_msg:   # checks for None or empty string
            commit_msg = None
```

**Comment by jimallman** [comment]
I just tested study deletion with only whitespace in the UI. This submits an empty string, which then fails to delete with this message:
```json
{
  "description": "Could not remove study #tt_33! Details: 

 RAN: '/usr/bin/git 
    --git-dir=/home/opentree/repo/phylesystem-0_par/phylesystem-0/.git 
    --work-tree=/home/opentree/repo/phylesystem-0_par/phylesystem-0 commit 
    --message= 
    --author=Jim Allman '

 STDOUT:


 STDERR:
Aborting commit due to empty commit message.
", 
  "error": 1
}
```

**Comment by jimallman** [comment]
Note that empty commit messages should be replaced by a non-empty default, as shown here:
https://github.com/OpenTreeOfLife/peyotl/blob/c5457ee292afc10bdcbc460410e8de1c3b339a51/peyotl/phylesystem/git_actions.py#L341-L342

**Comment by jimallman** [comment]
Tested successfully on **devapi**.

**Comment by mtholder** [comment]
I think that the logic on that line (https://github.com/OpenTreeOfLife/peyotl/blob/c5457ee292afc10bdcbc460410e8de1c3b339a51/peyotl/phylesystem/git_actions.py#L341 ), needs to be replaced with 3 lines:

    if commit_msg:
        commit_msg = commit_msg.strip()
    if not commit_msg:

to cover the cases of None, empty strings and white-space only strings.

**Comment by snacktavish** [comment]
I added that logic in peyotl, and a test with a with a whitespace commit message in phylesystem-api, and they pass, but I'm not sure the best way to check the content of the commit messages in the the phylesystem repo git log for the test. On my machine I can just check the log in the phylesystem-0 .git dir, but the test structure doesn’t generally have/need that directory location. Any ideas?

**Comment by jimallman** [comment]
> I'm not sure the best way to check the content of the commit messages in the the phylesystem repo git log for the test.

No great ideas at the moment. We can retrieve a study's git history with phylesystem-api, but only if it exists. :grimacing:

I just tried retrieved an old version of a study [using `starting_commit_SHA`](https://github.com/OpenTreeOfLife/phylesystem-api/blob/master/docs/README.md#get-arguments), but that returns an abbreviated history up to that version. Which is smart, but not helpful in this case.

**Pull request merged**
