### PR TITLE
Update CrossRef API calls

### PR DESCRIPTION
**Pull request by jimallman**
See background and related discussion in https://github.com/OpenTreeOfLife/opentree/issues/1193

This is tested and working now on **devapi**.

### CODE REVIEW

**Comment by snacktavish** [comment]
Is potentially interacting oddly with checking for duplicate doi. 
Didn't get a warning on creating study https://devtree.opentreeoflife.org/curator/study/view/tt_244, even though https://devtree.opentreeoflife.org/curator/study/view/tt_241 already existed.

Dup doi is recognized in tt_241, but not tt_244.

**Comment by jimallman** [comment]
@snacktavish I still have a few related updates to DOI lookup features elsewhere. Will make sure this is on my naughty list.

**Comment by snacktavish** [comment]
Was actually due to index lag from previous failed github webhooks. tt_244 was in the index, and tt_241 wasn't, which makes this behavior make sense! Changes in this branch not responsible.

**Comment by snacktavish** [comment]
Weird behavior was due to index lag. I poked it a bunch and everything seems good.

**Comment by jimallman** [comment]
OK, DOI lookup tool (in study editor) is now using the latest CrossRef APIs. It's a bit more tap-dancing, but seems to be working well even in cases where reference text has lots of funky Unicode. Tested and working on **devtree**.

**Pull request merged**
